import {
  atIsUnique,
  auth,
  bookmarkPost,
  decrement,
  fileReport,
  firestore,
  getServerTimestamp,
  getUserWithId,
  getUserWithTheirAt,
  increment,
  subscribeToInteractionWith,
  subscribeToUserWithId,
  subscribeToUserWithTheirAt,
  updateBio,
  updateLinks,
  updateUser,
} from "./firebase";
import { loginWithGoogle, signOut, subscribeToAuth } from "./auth";
import {
  incrementScore,
  unincrementScore,
  switchUpVoteToDownVote,
  decrementScore,
  undecrementScore,
  switchDownVoteToUpVote,
} from "./score";
import { followUser, unfollowUser, doesFollow, getFollowers } from "./follow";
import {
  writeComment,
  subscribeToComments,
  getCommentsForPost,
  subscribeToReplies,
  getRepliesToComment,
} from "./comments";
import {
  subscribeToMyFeed,
  subscribeToAnonFeed,
  getPostByDocId,
  getMyBookmarks,
  getPostsByIds,
  createPost,
} from "./posts";
import {
  getMyNotifications,
  writeNotification,
  updateNotifications,
} from "./notifications";

export {
  atIsUnique,
  auth,
  bookmarkPost,
  createPost,
  decrement,
  doesFollow,
  fileReport,
  firestore,
  followUser,
  getCommentsForPost,
  getFollowers,
  getMyBookmarks,
  getMyNotifications,
  getPostByDocId,
  getPostsByIds,
  getRepliesToComment,
  getServerTimestamp,
  getUserWithId,
  getUserWithTheirAt,
  increment,
  incrementScore,
  loginWithGoogle,
  signOut,
  subscribeToAnonFeed,
  subscribeToAuth,
  subscribeToComments,
  subscribeToInteractionWith,
  subscribeToMyFeed,
  subscribeToReplies,
  subscribeToUserWithId,
  subscribeToUserWithTheirAt,
  unfollowUser,
  updateBio,
  updateLinks,
  updateNotifications,
  updateUser,
  writeComment,
  writeNotification,
  decrementScore,
  switchDownVoteToUpVote,
  switchUpVoteToDownVote,
  undecrementScore,
  unincrementScore,
};
